[build]
  # Build command and publish directory
  command = "npm install && npm run build"
  publish = "dist"
  
  # Environment variables for build (non-sensitive only)
  # IMPORTANT: Set actual API keys in Netlify UI under Site Settings > Environment Variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"

# Configure secrets scanning to ignore placeholder values
# These are the placeholder values from .env.example that should be ignored
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "sk-ant-your-claude-key-here,xai-your-grok-key-here,AIza-your-gemini-key-here,gsk_your-groq-key-here"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Additional headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"